CORE_CONCEPTS = {
    # Pronouns
    "I": "Pronoun", "you": "Pronoun", "he": "Pronoun", "she": "Pronoun", "it": "Pronoun",
    "we": "Pronoun", "they": "Pronoun", "me": "Pronoun", "him": "Pronoun", "her": "Pronoun",
    "us": "Pronoun", "them": "Pronoun", "myself": "Pronoun", "yourself": "Pronoun",
    "himself": "Pronoun", "herself": "Pronoun", "itself": "Pronoun", "ourselves": "Pronoun",
    "themselves": "Pronoun", "mine": "Pronoun", "yours": "Pronoun", "hers": "Pronoun",
    "ours": "Pronoun", "theirs": "Pronoun", "whose": "Pronoun", "whoever": "Pronoun",
    "whatever": "Pronoun", "someone": "Pronoun", "anyone": "Pronoun", "everyone": "Pronoun",
    "nobody": "Pronoun", "something": "Pronoun", "anything": "Pronoun", "everything": "Pronoun",
    "nothing": "Pronoun", "which": "Pronoun", "whom": "Pronoun", "its": "Pronoun",
    # Question Words
    "who": "Pronoun", "what": "Pronoun", "where": "Adverb", "when": "Adverb",
    "why": "Adverb", "how": "Adverb",
    # Nouns - People & Creatures
    "person": "Noun", "man": "Noun", "woman": "Noun", "child": "Noun",
    "king": "Noun", "queen": "Noun", "friend": "Noun", "enemy": "Noun",
    "animal": "Noun", "fish": "Noun", "bird": "Noun", "dog": "Noun", "cat": "Noun",
    "father": "Noun", "mother": "Noun", "brother": "Noun", "sister": "Noun",
    "family": "Noun", "leader": "Noun", "soldier": "Noun", "teacher": "Noun",
    "student": "Noun", "farmer": "Noun", "hunter": "Noun", "merchant": "Noun",
    "horse": "Noun", "cow": "Noun", "sheep": "Noun", "pig": "Noun",
    "wolf": "Noun", "bear": "Noun", "snake": "Noun", "insect": "Noun",
    # Nouns - Nature & Elements
    "water": "Noun", "fire": "Noun", "earth": "Noun", "sky": "Noun",
    "wind": "Noun", "rain": "Noun", "snow": "Noun", "sun": "Noun", "moon": "Noun",
    "star": "Noun", "mountain": "Noun", "river": "Noun", "sea": "Noun", "forest": "Noun",
    "tree": "Noun", "seed": "Noun", "leaf": "Noun", "root": "Noun", "flower": "Noun",
    "stone": "Noun", "sand": "Noun", "clay": "Noun", "metal": "Noun",
    "gold": "Noun", "silver": "Noun", "iron": "Noun", "copper": "Noun",
    "cloud": "Noun", "storm": "Noun", "thunder": "Noun", "lightning": "Noun",
    "island": "Noun", "desert": "Noun", "field": "Noun", "valley": "Noun",
    "hill": "Noun", "lake": "Noun", "ocean": "Noun", "shore": "Noun",
    # Nouns - Body Parts
    "hand": "Noun", "foot": "Noun", "head": "Noun", "eye": "Noun", "ear": "Noun",
    "nose": "Noun", "mouth": "Noun", "heart": "Noun", "bone": "Noun", "blood": "Noun",
    "arm": "Noun", "leg": "Noun", "face": "Noun", "hair": "Noun", "skin": "Noun",
    "voice": "Noun", "tongue": "Noun", "tooth": "Noun", "back": "Noun",
    # Nouns - Places & Objects
    "home": "Noun", "house": "Noun", "village": "Noun", "town": "Noun", "city": "Noun",
    "road": "Noun", "path": "Noun", "bridge": "Noun", "gate": "Noun", "door": "Noun",
    "window": "Noun", "wall": "Noun", "room": "Noun", "table": "Noun", "chair": "Noun",
    "bed": "Noun", "fireplace": "Noun", "book": "Noun", "letter": "Noun", "map": "Noun",
    "tool": "Noun", "knife": "Noun", "sword": "Noun", "shield": "Noun", "bow": "Noun",
    "arrow": "Noun", "ship": "Noun", "boat": "Noun", "coin": "Noun", "banner": "Noun",
    # Nouns - Abstract
    "life": "Noun", "death": "Noun", "love": "Noun", "fear": "Noun",
    "time": "Noun", "day": "Noun", "night": "Noun", "dream": "Noun",
    "thought": "Noun", "memory": "Noun", "power": "Noun", "light": "Noun", "darkness": "Noun",
    "truth": "Noun", "lie": "Noun", "peace": "Noun", "war": "Noun", "honor": "Noun",
    "name": "Noun", "language": "Noun", "song": "Noun", "story": "Noun", "law": "Noun",
    "order": "Noun", "chaos": "Noun", "hope": "Noun", "fortune": "Noun", "fate": "Noun",
    # Verbs - Basic Actions
    "be": "Verb", "have": "Verb", "do": "Verb", "make": "Verb", "go": "Verb", "come": "Verb",
    "see": "Verb", "hear": "Verb", "know": "Verb", "think": "Verb", "say": "Verb",
    "speak": "Verb", "give": "Verb", "take": "Verb", "eat": "Verb", "drink": "Verb",
    "sleep": "Verb", "wake": "Verb", "walk": "Verb", "run": "Verb", "fly": "Verb",
    "stand": "Verb", "sit": "Verb", "fall": "Verb", "rise": "Verb", "carry": "Verb",
    "open": "Verb", "close": "Verb", "burn": "Verb", "grow": "Verb", "fight": "Verb",
    "build": "Verb", "destroy": "Verb", "find": "Verb", "lose": "Verb", "remember": "Verb",
    "forget": "Verb", "live": "Verb", "die": "Verb", "love": "Verb", "hate": "Verb",
    "work": "Verb", "play": "Verb", "read": "Verb", "write": "Verb", "listen": "Verb",
    "watch": "Verb", "learn": "Verb", "teach": "Verb", "help": "Verb", "move": "Verb",
    "send": "Verb", "bring": "Verb", "keep": "Verb", "hold": "Verb", "meet": "Verb",
    "follow": "Verb", "start": "Verb", "stop": "Verb", "change": "Verb", "ask": "Verb",
    "answer": "Verb", "use": "Verb", "become": "Verb", "create": "Verb", "return": "Verb",
    "am": "Verb", "is": "Verb", "are": "Verb", "was": "Verb", "were": "Verb",
    "been": "Verb", "being": "Verb", "has": "Verb", "had": "Verb", "does": "Verb",
    "did": "Verb", "will": "Verb", "shall": "Verb", "would": "Verb", "should": "Verb",
    "can": "Verb", "could": "Verb", "may": "Verb", "might": "Verb", "must": "Verb",
    # Adjectives
    "good": "Adjective", "bad": "Adjective", "big": "Adjective", "small": "Adjective",
    "long": "Adjective", "short": "Adjective", "new": "Adjective", "old": "Adjective",
    "young": "Adjective", "red": "Adjective", "green": "Adjective", "blue": "Adjective",
    "yellow": "Adjective", "white": "Adjective", "black": "Adjective", "bright": "Adjective",
    "dark": "Adjective", "strong": "Adjective", "weak": "Adjective", "happy": "Adjective",
    "sad": "Adjective", "hot": "Adjective", "cold": "Adjective", "empty": "Adjective",
    "full": "Adjective", "beautiful": "Adjective", "ugly": "Adjective", "fast": "Adjective",
    "slow": "Adjective", "heavy": "Adjective", "hard": "Adjective", "soft": "Adjective",
    "deep": "Adjective", "shallow": "Adjective", "high": "Adjective", "low": "Adjective",
    "safe": "Adjective", "dangerous": "Adjective", "true": "Adjective", "false": "Adjective",
    "open": "Adjective", "closed": "Adjective", "early": "Adjective", "late": "Adjective",
    # Adverbs
    "not": "Adverb", "very": "Adverb", "quickly": "Adverb", "slowly": "Adverb",
    "now": "Adverb", "soon": "Adverb", "always": "Adverb", "never": "Adverb",
    "here": "Adverb", "there": "Adverb", "everywhere": "Adverb", "often": "Adverb",
    "sometimes": "Adverb", "again": "Adverb", "together": "Adverb", "apart": "Adverb",
    "inside": "Adverb", "outside": "Adverb", "away": "Adverb", "already": "Adverb",
    "perhaps": "Adverb", "maybe": "Adverb",
    # Prepositions
    "in": "Preposition", "on": "Preposition", "at": "Preposition", "to": "Preposition",
    "from": "Preposition", "with": "Preposition", "without": "Preposition", "under": "Preposition",
    "over": "Preposition", "between": "Preposition", "before": "Preposition", "after": "Preposition",
    "into": "Preposition", "out": "Preposition", "through": "Preposition", "across": "Preposition",
    "around": "Preposition", "near": "Preposition", "against": "Preposition", "among": "Preposition",
    "during": "Preposition", "until": "Preposition", "within": "Preposition",
    # Conjunctions
    "and": "Conjunction", "or": "Conjunction", "but": "Conjunction",
    "if": "Conjunction", "because": "Conjunction", "although": "Conjunction",
    "while": "Conjunction", "nor": "Conjunction", "yet": "Conjunction",
    "unless": "Conjunction", "since": "Conjunction",
    # Determiners
    "all": "Determiner", "some": "Determiner", "many": "Determiner", "few": "Determiner",
    "this": "Determiner", "that": "Determiner", "these": "Determiner", "those": "Determiner",
    "the": "Determiner", "a": "Determiner", "an": "Determiner", "any": "Determiner",
    "every": "Determiner", "each": "Determiner", "either": "Determiner",
    "neither": "Determiner", "no": "Determiner", "another": "Determiner", "such": "Determiner",
    # Numbers
    "one": "Number", "two": "Number", "three": "Number", "four": "Number", "five": "Number",
    "six": "Number", "seven": "Number", "eight": "Number", "nine": "Number", "ten": "Number",
    "eleven": "Number", "twelve": "Number", "thirteen": "Number", "fourteen": "Number",
    "fifteen": "Number", "sixteen": "Number", "seventeen": "Number", "eighteen": "Number",
    "nineteen": "Number", "twenty": "Number", "hundred": "Number", "thousand": "Number",
    # Contractions & Common Variants
    "it's": "Verb", "i'm": "Verb", "you're": "Verb", "we're": "Verb", "they're": "Verb",
    "he's": "Verb", "she's": "Verb", "that's": "Verb", "there's": "Verb", "what's": "Verb",
    "who's": "Verb", "can't": "Verb", "cannot": "Verb", "won't": "Verb", "don't": "Verb",
    "doesn't": "Verb", "didn't": "Verb", "isn't": "Verb", "aren't": "Verb",
    "wasn't": "Verb", "weren't": "Verb", "shouldn't": "Verb", "wouldn't": "Verb",
    "couldn't": "Verb", "mustn't": "Verb", "haven't": "Verb", "hasn't": "Verb",
    "hadn't": "Verb", "should've": "Verb", "would've": "Verb", "could've": "Verb",
    "must've": "Verb", "i've": "Verb", "you've": "Verb", "we've": "Verb", "they've": "Verb",
    "i'll": "Verb", "you'll": "Verb", "we'll": "Verb", "they'll": "Verb",
    "he'll": "Verb", "she'll": "Verb", "i'd": "Verb", "you'd": "Verb", "we'd": "Verb",
    "they'd": "Verb", "he'd": "Verb", "she'd": "Verb", "let's": "Verb",
    "im": "Verb", "youre": "Verb", "theyre": "Verb", "ive": "Verb", "youve": "Verb",
    "weve": "Verb", "theyve": "Verb", "dont": "Verb", "doesnt": "Verb", "didnt": "Verb",
    "cant": "Verb", "wont": "Verb", "isnt": "Verb", "arent": "Verb", "wasnt": "Verb",
    "werent": "Verb", "havent": "Verb", "hasnt": "Verb", "hadnt": "Verb",
    "havnt": "Verb", "havn't": "Verb", "shouldve": "Verb", "wouldve": "Verb",
    "couldve": "Verb", "mustve": "Verb",
    # Common Phrases
    "hello": "Phrase", "goodbye": "Phrase", "please": "Phrase", "thank you": "Phrase",
    "good morning": "Phrase", "good night": "Phrase", "excuse me": "Phrase",
    "i am sorry": "Phrase", "how are you": "Phrase", "see you": "Phrase",
}

